export const COLUMNS_TEST = [
  'EventID',
  'EventName',
  'EventDate',
  'BetType',
  'EventChanceTypeID',
  'LiveBetting',
  'SportEventID',
  'SportID',
  'RegionID',
  'LeagueCupID',
  'ChanceTypeID',
  'ChanceTypeName',
  'SideBet',
  'ActualGamePartID',
  'ActualGamePartTime',
  'EventChanceTypeStatus',
  'LiveFeedReference',
  'LiveBettingView',
];
export const COLUMNS_MATCHES = ['EventName', 'EventDate', 'Sport', 'League', 'BetRate'];
